var styleprint = {classes:
[{class:"background{fill: none}"},
{class:"chartholder{fill: none}"},
{class:"title{font-family:Avenir; font-size:12px; line-height:13px; fill:#000000; font-weight:900;}"},
{class:"subtitle{font-family:Avenir; font-style:italic; fill:#000000; font-size:9.5px; line-height:11px; font-weight:100; letter-spacing:-.2px;}"},
{class:"legend{font-family:Avenir; font-size:10px; line-height:11px; font-weight: 100; fill: #000;}"},
{class:"labels{font-family:Avenir; font-size:10px; line-height:11px; fill:#fff; font-weight: 100;}"},
{class:"source{fill: #000000; font-family:Avenir; font-style:italic; font-size:8.5px; line-height:9px; font-weight:100; letter-spacing:-.2px;}"},
{class:"logo{fill: none;}"},
{class:"hat{fill:none; stroke-width:0.3px; stroke:#000;}"},
{class:"xAxis{fill:none; stroke-width:0.3px; stroke:#acacac;}"},
{class:"xAxis line{fill:none; stroke-width:2.5px; stroke:#000; stroke-linecap:round;}"},
{class:"xAxis text{fill:#000000; font-family: Avenir; font-size:10px; line-height:11px; font-weight:100; letter-spacing:-.2px; font-feature-settings:'tnum' 1;}"},
{class:"yAxis{fill:none; stroke-width:0.3px; stroke:#acacac;}"},
{class:"yAxis line{fill:none; stroke-width:0.3px; stroke:#acacac;}"},
{class:"yAxis text{fill:#000000; font-family: Avenir; font-size:10px; line-height:11px; font-weight:100; letter-spacing:-.2px; font-feature-settings:'tnum' 1;}"},
{class:"origin line{fill:none; stroke-width:0.5px; stroke:#000;}"},
{class:"whiskers{fill:none; stroke-width:1.0px;stroke:#22190f;}"},
{class:"lines{fill:none; stroke-width:2.0px;stroke-linecap: round;}"},
{class:"linesHighlight{fill:none; stroke-width:.3px; stroke:#000;}"},
{class:"fill{fill-opacity:1.0; stroke-width: 0.0px}"},
{class:"highlight{fill-opacity:1.0;}"},
{class:"day{fill:none; stroke: #ffffff; stroke-width:1.0px;stroke-linecap: round;}"},
{class:"month{fill:none; stroke: #000000; stroke-width:1.0px;stroke-linecap: round;}"}
],
titleOffset:12,
subOffset:-5,
legendyOffset:0,
linecolours:["#154577","#58bdbb","#ac252a","#cabd92","#ee5427","#f9a71a","#b0d480","#64a056","#00809c","#675388","#a16698","#d2d3d3"],
fillcolours:["#154577","#58bdbb","#ac252a","#cabd92","#ee5427","#f9a71a","#b0d480","#64a056","#00809c","#675388","#a16698","#d2d3d3"]
}

var styleweb = {classes:
[{class:"background{fill: none}"},
{class:"chartholder{fill: none}"},
{class:"title{font-family:Avenir; font-size:12px; line-height:13px; fill:#000000; font-weight:900;}"},
{class:"subtitle{font-family:Avenir; font-style:italic; fill:#000000; font-size:9.5px; line-height:11px; font-weight:100; letter-spacing:-.2px;}"},
{class:"legend{font-family:Avenir; font-size:10px; line-height:11px; font-weight: 100; fill: #000;}"},
{class:"labels{font-family:Avenir; font-size:10px; line-height:11px; fill:#fff; font-weight: 100;}"},
{class:"source{fill: #000000; font-family:Avenir; font-style:italic; font-size:8.5px; line-height:9px; font-weight:100; letter-spacing:-.2px;}"},
{class:"logo{fill: none;}"},
{class:"hat{fill:none; stroke-width:0.3px; stroke:#000;}"},
{class:"xAxis{fill:none; stroke-width:0.3px; stroke:#acacac;}"},
{class:"xAxis line{fill:none; stroke-width:2.5px; stroke:#000; stroke-linecap:round;}"},
{class:"xAxis text{fill:#000000; font-family: Avenir; font-size:10px; line-height:11px; font-weight:100; letter-spacing:-.2px; font-feature-settings:'tnum' 1;}"},
{class:"yAxis{fill:none; stroke-width:0.3px; stroke:#acacac;}"},
{class:"yAxis line{fill:none; stroke-width:0.3px; stroke:#acacac;}"},
{class:"yAxis text{fill:#000000; font-family: Avenir; font-size:10px; line-height:11px; font-weight:100; letter-spacing:-.2px; font-feature-settings:'tnum' 1;}"},
{class:"origin line{fill:none; stroke-width:0.5px; stroke:#000;}"},
{class:"whiskers{fill:none; stroke-width:1.0px;stroke:#22190f;}"},
{class:"lines{fill:none; stroke-width:2.0px;stroke-linecap: round;}"},
{class:"linesHighlight{fill:none; stroke-width:.3px; stroke:#000;}"},
{class:"fill{fill-opacity:1.0; stroke-width: 0.0px}"},
{class:"highlight{fill-opacity:1.0;}"},
{class:"day{fill:none; stroke: #ffffff; stroke-width:1.0px;stroke-linecap: round;}"},
{class:"month{fill:none; stroke: #000000; stroke-width:1.0px;stroke-linecap: round;}"}
],
titleOffset:12,
subOffset:-5,
legendyOffset:0,
linecolours:["#154577","#58bdbb","#ac252a","#cabd92","#ee5427","#f9a71a","#b0d480","#64a056","#00809c","#675388","#a16698","#d2d3d3"],
fillcolours:["#154577","#58bdbb","#ac252a","#cabd92","#ee5427","#f9a71a","#b0d480","#64a056","#00809c","#675388","#a16698","#d2d3d3"]
}

var stylesoc = {classes:
[{class:"background{fill: none}"},
{class:"chartholder{fill: none}"},
{class:"title{font-family:Avenir; font-size:12px; line-height:13px; fill:#000000; font-weight:900;}"},
{class:"subtitle{font-family:Avenir; font-style:italic; fill:#000000; font-size:9.5px; line-height:11px; font-weight:100; letter-spacing:-.2px;}"},
{class:"legend{font-family:Avenir; font-size:10px; line-height:11px; font-weight:100; fill:#000;}"},
{class:"labels{font-family:Avenir; font-size:10px; line-height:11px; fill:#fff; font-weight:100;}"},
{class:"source{fill: #000000; font-family:Avenir; font-style:italic; font-size:8.5px; line-height:9px; font-weight:100; letter-spacing:-.2px;}"},
{class:"logo{fill: none;}"},
{class:"hat{fill:none; stroke-width:0.3px; stroke:#000;}"},
{class:"xAxis{fill:none; stroke-width:0.3px; stroke:#acacac;}"},
{class:"xAxis line{fill:none; stroke-width:2.5px; stroke:#000; stroke-linecap:round;}"},
{class:"xAxis text{fill:#000000; font-family: Avenir; font-size:10px; line-height:11px; font-weight:100; letter-spacing:-.2px; font-feature-settings:'tnum' 1;}"},
{class:"yAxis{fill:none; stroke-width:0.3px; stroke:#acacac;}"},
{class:"yAxis line{fill:none; stroke-width:0.3px; stroke:#acacac;}"},
{class:"yAxis text{fill:#000000; font-family: Avenir; font-size:10px; line-height:11px; font-weight:100; letter-spacing:-.2px; font-feature-settings:'tnum' 1;}"},
{class:"origin line{fill:none; stroke-width:0.5px; stroke:#000;}"},
{class:"whiskers{fill:none; stroke-width:1.0px;stroke:#22190f;}"},
{class:"lines{fill:none; stroke-width:2.0px;stroke-linecap:round;}"},
{class:"linesHighlight{fill:none; stroke-width:.3px; stroke:#000;}"},
{class:"fill{fill-opacity:1.0; stroke-width:0.0px}"},
{class:"highlight{fill-opacity:1.0;}"},
{class:"day{fill:none; stroke: #ffffff; stroke-width:1.0px;stroke-linecap: round;}"},
{class:"month{fill:none; stroke: #000000; stroke-width:1.0px;stroke-linecap: round;}"}
],
titleOffset:12,
subOffset:-5,
legendyOffset:0,
linecolours:["#154577","#58bdbb","#ac252a","#cabd92","#ee5427","#f9a71a","#b0d480","#64a056","#00809c","#675388","#a16698","#d2d3d3"],
fillcolours:["#154577","#58bdbb","#ac252a","#cabd92","#ee5427","#f9a71a","#b0d480","#64a056","#00809c","#675388","#a16698","#d2d3d3"]
}

var stylevid = {classes:
[{class:"background{fill: #212121;}"},
{class:"titleframe{fill: none;}"},
{class:"chartholder{fill: none;}"},
{class:"title{font-size: 68px; fill: #ffffff; font-weight: 600;opacity: 0.9;}"},
{class:"subtitle{font-size: 48; fill: #ffffff; font-weight: 400;opacity: 0.7;}"},
{class:"source{font-size: 36; fill: #ffffff; font-weight: 400;opacity: 0.5;}"},
{class:"logo{fill: #ffffff;}"},
{class:"xAxis{fill:none; stroke: none;}"},
{class:"xAxis line{fill:none; stroke-width: 4px; stroke:#ffffff;opacity: 0.5}"},
{class:"xAxis text{font-size: 48; fill: #ffffff; font-weight: 400;opacity: 0.5}"},
{class:"yAxis{fill:none; stroke: none;}"},
{class:"yAxis line{fill:none; stroke-width: 4px; stroke:#ffffff;opacity: 0.38}"},
{class:"yAxis text{font-size: 48; fill: #ffffff; font-weight: 400;font-feature-settings: 'tnum' 1; text-anchor: end;opacity: 0.5}"},
{class:"origin line{fill:none; stroke:#ffffff; stroke-width: 5.0px;stroke-dasharray:1,0; opacity: 0.5}"},
{class:"whiskers{fill:none; stroke-width:2.0px;stroke:#ffffff; opacity: 0.5}"},
{class:"lines{fill:none; stroke-width: 8.0px; stroke-linecap: round;stroke-linejoin: round;}"},
{class:"fill{fill-opacity:1.0; stroke-width: 0.0px}"},
{class:"highlight{fill-opacity:1.0;}"},
{class:"day{fill:none; stroke: #ffffff; stroke-width:4.0px; opacity: 0.5; stroke-linecap: round;stroke-linejoin: round;}"},
{class:"month{fill:none; stroke: #ffffff; stroke-width:4.0px; opacity: 0.5; stroke-linecap: round;stroke-linejoin: round;}"}

],
titleOffset:68,
subOffset:0,
legendyOffset:15,
linecolours:["#EB3F50","#00D9CA","#BF9413","#1F5E99","#A7FF59","#FF9B96","#81838F"],
fillcolours:["#EB3F50","#00D9CA","#BF9413","#1F5E99","#A7FF59","#FF9B96","#81838F"]
}
