var styleprint = {classes:
[{class:"background{fill: none}"},
{class:"chartholder{fill: none}"},
{class:"title{font-family:Avenir; font-size:10px; line-height:11px; fill:#000000; font-weight:900;}"},
{class:"subtitle{font-family:Avenir; font-style:italic; fill:#000000; font-size:7.5px; line-height:9px; font-weight:100; letter-spacing:-.2px;}"},
{class:"legend{font-family:Avenir; font-size:8px; line-height:9px; font-weight: 100; fill: #000;}"},
{class:"circLabel{fill:#000000; font-family: Avenir; font-size:8px; line-height:9px; font-weight: 100; text-anchor: middle;}"},
{class:"labels{font-family:Avenir; font-size:8px; line-height:9px; fill: #000; font-weight: 100;}"},
{class:"source{fill: #000000; font-family:Avenir; font-style:italic; font-size:6.5px; line-height: 7px; font-weight: 100;}"},
{class:"logo{fill: none;}"},
{class:"hat{fill:none; stroke-width:0.75px; stroke:#000;}"},
{class:"xAxis{fill:none; stroke-width:0px; stroke:none;}"},
{class:"xAxis line{fill:none; stroke-width:.3px; stroke:#acacac;}"},
{class:"xAxis text{fill:#000000; font-family: Avenir; font-size:8px; line-height:9px; font-weight: 100; font-feature-settings:'tnum' 1;}"},
{class:"yAxis{fill:none; stroke-width:0px; stroke:none;}"},
{class:"yAxis line{fill:none; stroke-width:0.3px; stroke:#acacac;}"},
{class:"yAxis text{fill:#000000; font-family: Avenir; font-size: 8px; line-height:9px; font-weight: 100; font-feature-settings: 'tnum' 1;}"},
{class:"origin line{fill:none; stroke-width:0.5px; stroke:#000;}"},
{class:"whiskers{fill:none; stroke-width:1.0px;stroke:#22190f;}"},
{class:"lines{fill:none; stroke-width:2.0px;stroke-linecap: round;}"},
{class:"linesHighlight{fill:none; stroke-width:.3px; stroke:#000;}"},
{class:"fill{opacity: .38}"},
{class:"highlight{fill-opacity:0.5; stroke: #000000; stroke-width: 1.0px}"},
{class:"day{fill:none; stroke: #ffffff; stroke-width:1.0px;stroke-linecap: round;}"},
{class:"month{fill:none; stroke: #000000; stroke-width:1.0px;stroke-linecap: round;}"},
{class:"link{fill:none; stroke:#000000; opacity: 0.20;}"},
{class:"node{fill:#000000;}"}
],
titleOffset:9,
subOffset:-4,
legendyOffset:0,
linecolours:["#154577","#58bdbb","#cabd92","#ac252a","#ee5427","#f9a71a","#b0d480","#009a8e","#00809c","#675388","#a16698","#d2d3d3"],
fillcolours:["#154577","#58bdbb","#cabd92","#ac252a","#ee5427","#f9a71a","#b0d480","#009a8e","#00809c","#675388","#a16698","#d2d3d3"]
}

var styleweb = {classes:
[{class:"background{fill: none}"},
{class:"chartholder{fill: none;}"},
{class:"title{font-size:17px; font-family:Avenir; line-height:18px; font-weight:900; fill:#000;}"},
{class:"subtitle{font-family:Avenir; font-style:italic; font-size:12.75px; line-height:15.3px; font-weight:100; fill:#000; letter-spacing:-.2px;}"},
{class:"legend{font-family:Avenir; font-size:13.6px; line-height:15.3px; font-weight: 100; fill: #000;}"},
{class:"circLabel{font-family:Avenir; fill:#000; font-size:13.6px; line-height:15.3; font-weight:100; text-anchor: middle;}"},
{class:"source{fill:#000; font-family:Avenir; font-style:italic; font-size:11px; line-height:12px; font-weight:100;}"},
{class:"labels{font-family:Avenir; font-size:13.6px; line-height:15.3px; fill:#000; font-weight:100;}"},
{class:"logo{fill: none;}"},
{class:"hat{fill:none; stroke-width:1.3px; stroke:#000;}"},
{class:"xAxis{fill:none; stroke: none;}"},
{class:"xAxis line{fill:none; stroke-width: .5px; stroke:#acacac;}"},
{class:"xAxis text{font-family:Avenir; fill:#000; font-size:13.6px; line-height:15.3; font-weight:100;}"},
{class:"yAxis{fill:none; stroke: none;}"},
{class:"yAxis line{fill:none; stroke-width:.5px; stroke:#acacac;}"},
{class:"yAxis text{font-family: Avenir; fill:#000; font-size: 13.6px; line-height:15.3; font-weight: 100; font-feature-settings: 'tnum' 1; text-anchor: end;}"},
{class:"origin line{fill:none; stroke:#000; stroke-width:.85px;}"},
{class:"whiskers{fill:none; stroke-width:1.0px;stroke:#22190f;}"},
{class:"lines{fill:none; stroke-width: 2.5px; stroke-linecap: round;}"},
{class:"linesHighlight{fill:none; stroke-width:.5px; stroke:#000;}"},
{class:"fill{opacity: .38}"},
{class:"highlight{fill-opacity:0.5; stroke: #000000; stroke-width: 1.5px}"},
{class:"day{fill:none;stroke: #fff1e0; stroke-width:1.0px;stroke-linecap: round;}"},
{class:"month{fill:none;stroke: #000000; stroke-width:1.0px;stroke-linecap: round;}"},
{class:"link{fill:none; stroke:#000000; opacity: 0.20;}"},
{class:"node{fill:#000000;}"}
],
titleOffset:29,
subOffset:-7,
legendyOffset:0,
linecolours:["#154577","#58bdbb","#cabd92","#ac252a","#ee5427","#f9a71a","#b0d480","#009a8e","#00809c","#675388","#a16698","#d2d3d3"],
fillcolours:["#154577","#58bdbb","#cabd92","#ac252a","#ee5427","#f9a71a","#b0d480","#009a8e","#00809c","#675388","#a16698","#d2d3d3"]
}

var stylesoc = {classes:
[{class:"background{fill: #212121;}"},
{class:"chartholder{fill: none;}"},
{class:"title{font-size: 38px; fill: #ffffff; font-weight: 600; opacity: 0.9;}"},
{class:"subtitle{font-size: 28px; fill: #ffffff; font-weight: 400; opacity: 0.7;}"},
{class:"circLabel{font-size: 28px; fill: #ffffff; font-weight: 400; opacity: 0.7;text-anchor: middle;}"},
{class:"labels{font-size: 28px; fill: #ffffff; opacity: 0.5; font-weight: 400;}"},
{class:"source{font-size: 25px; fill: #ffffff; font-weight: 400; opacity: 0.5;}"},
{class:"logo{fill: #ffffff; opacity: 0.38;}"},
{class:"xAxis{fill:none; stroke: none;}"},
{class:"xAxis line{fill:none; stroke:#ffffff; stroke-width: 2.0px; stroke-dasharray:2,8; opacity: 0.5;}"},
{class:"xAxis text{font-size: 28px; fill: #ffffff; font-weight: 400; opacity: 0.5;}"},
{class:"yAxis{fill:none; stroke: none;}"},
{class:"yAxis line{fill:none; stroke-width: 2.0px; stroke-dasharray:2,8; opacity: 0.38; stroke:#ffffff;}"},
{class:"yAxis text{font-size: 28px; fill: #ffffff; font-weight: 400; opacity: 0.5; font-feature-settings: 'tnum' 1; text-anchor: end;}"},
{class:"origin line{fill:none; stroke:#ffffff; stroke-width: 2.0px; opacity: 0.5; stroke-dasharray: 1,0}"},
{class:"whiskers{fill:none; stroke-width:2.0px;stroke:#ffffff; opacity: 0.5}"},
{class:"lines{fill:none; stroke-width: 5px;  stroke-linecap: round;}"},
{class:"linesHighlight{fill:none; stroke-width:.8px;stroke-linecap: round;}"},
{class:"fill{opacity: .38}"},
{class:"highlight{fill-opacity:0.5; stroke: #ffffff; stroke-width: 2.0px}"},
{class:"day{fill:none; stroke: #ffffff; stroke-width:1.0px; opacity: 0.5; stroke-linecap: round;}"},
{class:"month{fill:none; stroke: #ffffff; stroke-width:1.0px; opacity: 0.5; stroke-linecap: round;}"},
{class:"link{fill:none; stroke:#ffffff; opacity: 0.20;}"},
{class:"node{fill:#000000; }"}
],
titleOffset:36,
subOffset:0,
legendyOffset:0,
linecolours:["#EB3F50","#00D9CA","#BF9413","#1F5E99","#A7FF59","#FF9B96","#81838F"],
fillcolours:["#EB3F50","#00D9CA","#BF9413","#1F5E99","#A7FF59","#FF9B96","#81838F"]
}

var stylevid = {classes:
[{class:"background{fill: #dfd0bd;}"},
{class:"titleframe{fill: #757575;}"},
{class:"chartholder{fill: none;}"},
{class:"title{font-size: 68px; fill: #ffffff; font-weight: 600;}"},
{class:"subtitle{font-size: 48; fill: #000000; font-weight: 600;}"},
{class:"circLabel{font-size: 48; fill: #000000; font-weight: 600;text-anchor: middle;}"},
{class:"source{font-size: 44; fill: #000000; font-weight: 600;}"},
{class:"labels{font-size:10px; fill: #ffffff; font-weight: 300;}"},
{class:"logo{fill: #ffffff;}"},
{class:"xAxis{fill:none; stroke: none;}"},
{class:"xAxis line{fill:none; stroke-width: 5.0px; stroke:#ffffff;}"},
{class:"xAxis text{font-size: 48; fill: #000000; font-weight: 600;}"},
{class:"yAxis{fill:none; stroke: none;}"},
{class:"yAxis line{fill:none; stroke-width: 5.0px; stroke:#ffffff;}"},
{class:"yAxis text{font-size: 48; fill: #000000; font-weight: 600;font-feature-settings: 'tnum' 1; text-anchor: end;}"},
{class:"origin line{fill:none; stroke:#ffffff; stroke-width: 5.0px;stroke-dasharray:1,0}"},
{class:"whiskers{fill:none; stroke-width:2.0px;stroke:#ffffff; opacity: 0.5}"},
{class:"lines{fill:none; stroke-width: 8.0px; stroke-linecap: round;}"},
{class:"linesHighlight{fill:none; stroke-width:.8px;stroke-linecap: round;}"},
{class:"fill{opacity: .38}"},
{class:"highlight{fill-opacity:0.5; stroke: #ffffff; stroke-width: 4.0px}"},
{class:"day{fill:none; stroke: #ffffff; stroke-width:1.0px; opacity: 0.5; stroke-linecap: round;}"},
{class:"month{fill:none; stroke: #ffffff; stroke-width:1.0px; opacity: 0.5; stroke-linecap: round;}"},
{class:"link{fill:none; stroke:#ffffff; opacity: 0.20;}"},
{class:"node{fill:#000000; }"}

],
titleOffset:68,
subOffset:0,
legendyOffset:15,
linecolours:["#b34b41","#5a8caf","#9baa6e","#eda45e","#9c5f87","#486ba0"]
}
